apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata:
  name: vsan-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagePolicyName: "vSAN Default Storage Policy"
  datastore: vsanDatastore
