apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: second-index
  name: second-index
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-index
  template:
    metadata:
      labels:
        app: second-index
    spec:
      volumes:
      - name: second
        pathPath: 
          path: /root/ss-test/second/index.html
      containers:
      - image: nginx:1.18
        name: container
        volumeMounts:
        - name: second
          mountPath: /usr/share/nginx/html/index.html
